declare module 'fake-indexeddb/build/fakeIndexedDB.js' {}
declare module 'fake-indexeddb/build/FDBCursor.js' {}
declare module 'fake-indexeddb/build/FDBCursorWithValue.js' {}
declare module 'fake-indexeddb/build/FDBDatabase.js' {}
declare module 'fake-indexeddb/build/FDBFactory.js' {}
declare module 'fake-indexeddb/build/FDBIndex.js' {}
declare module 'fake-indexeddb/build/FDBKeyRange.js' {}
declare module 'fake-indexeddb/build/FDBObjectStore.js' {}
declare module 'fake-indexeddb/build/FDBOpenDBRequest.js' {}
declare module 'fake-indexeddb/build/FDBRequest.js' {}
declare module 'fake-indexeddb/build/FDBTransaction.js' {}
declare module 'fake-indexeddb/build/FDBVersionChangeEvent.js' {}
